# Generated by Django 3.1.7 on 2021-04-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SudokuGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_board', models.CharField(max_length=200)),
                ('current_board', models.CharField(max_length=200)),
                ('solution_board', models.CharField(max_length=200)),
            ],
        ),
    ]
