# Generated by Django 3.1.7 on 2021-04-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudokugame',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='easy', max_length=10),
        ),
    ]
