# Generated by Django 3.1.7 on 2021-04-12 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sudoku_app', '0004_userstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SudokuRecord',
            fields=[
                ('puzzle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='sudokugame',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=10),
        ),
        migrations.DeleteModel(
            name='UserStatistics',
        ),
    ]
